// filepath: /workspaces/msfs-top-aircraft/helm/templates/migrate-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
  labels:
    app: prisma-migrate
    release: {{ .Release.Name }}
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 300  # 5 minutes timeout for the job
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: {{ .Values.migrate.image }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: DATABASE_URL
          command: ["npx", "prisma", "migrate", "deploy", "--schema=prisma/schema.prisma"]
