apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate-{{ .Release.Revision }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    # Keep the old Helm hooks for direct helm installations
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app: prisma-migrate
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  backoffLimit: 3
  template:
    metadata:
      annotations:
        # Add a checksum annotation to force job recreation when schema changes
        checksum/schema: {{ include (print $.Template.BasePath "/migrate-configmap.yaml") . | sha256sum }}
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: {{ .Values.migrate.image }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: DATABASE_URL
          command: ["sh", "-c", "npx prisma migrate deploy && node dist/import-initial-data.js"] 