apiVersion: v1
kind: ConfigMap
metadata:
  name: prisma-schema
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  # This is not used directly, just for checksum calculation
  schema.prisma: |
    {{ .Files.Get "schema.prisma" | default "# Default schema if not mounted" | indent 4 }}
