{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secret.data.DATABASE_URL | b64enc | quote }}
  SESSION_SECRET: {{ .Values.secret.data.SESSION_SECRET | b64enc | quote }}
  ADMIN_USER: {{ .Values.secret.data.ADMIN_USER | b64enc | quote }}
  ADMIN_PASS: {{ .Values.secret.data.ADMIN_PASS | b64enc | quote }}
{{- end }} 