FROM node:20-alpine
WORKDIR /prisma
COPY ../package.json ../package-lock.json ./
RUN npm ci --omit=dev
COPY . .
COPY ../node_modules ./node_modules
ENV NODE_ENV=production
CMD ["npx", "prisma", "migrate", "deploy"] 