frontend:
  image: "ghcr.io/desponda/msfs-top-aircraft/frontend:6f3d2ea47ac70ad2dc3261a3a9785e20bcc22349"
  replicaCount: 2
  ingress:
    enabled: true
    host: msfs.example.com
    ingressClassName: nginx
  env:
    VITE_API_URL: "https://msfs.example.com/api"
backend:
  image: "ghcr.io/desponda/msfs-top-aircraft/backend:6f3d2ea47ac70ad2dc3261a3a9785e20bcc22349"
  replicaCount: 2
  env:
    NODE_ENV: "production"
migrate:
  image: "ghcr.io/desponda/msfs-top-aircraft/migrate:6f3d2ea47ac70ad2dc3261a3a9785e20bcc22349"
  env: {}
secret:
  enabled: true
  name: msfs-secrets
  data:
    DATABASE_URL: ""
    SESSION_SECRET: ""
    ADMIN_USER: ""
    ADMIN_PASS: ""
