frontend:
  image: "ghcr.io/desponda/msfs-top-aircraft/frontend:c9e6588b8752e4f623d2776cd49e9ca2cb62c520"
  replicaCount: 2
  ingress:
    enabled: true
    host: msfs.example.com
    ingressClassName: nginx
  env:
    VITE_API_URL: "https://msfs.example.com/api"
backend:
  image: "ghcr.io/desponda/msfs-top-aircraft/backend:c9e6588b8752e4f623d2776cd49e9ca2cb62c520"
  replicaCount: 2
  env:
    NODE_ENV: "production"
migrate:
  image: "ghcr.io/desponda/msfs-top-aircraft/migrate:c9e6588b8752e4f623d2776cd49e9ca2cb62c520"
  env: {}
secret:
  enabled: true
  name: msfs-secrets
  data:
    DATABASE_URL: ""
    SESSION_SECRET: ""
    ADMIN_USER: ""
    ADMIN_PASS: ""
